### ISSUE TITLE
SyntaxError: expected OPTIONAL

### ISSUE THREAD

**Issue by KonradHoeffner** [oxigraph/oxrdflib#9]
oxrdflib 0.3.0 with rdflib 6.1.1 with the following simple query causes a syntax error. However when not using `store="Oxigraph` it does not cause this error.

## Example

```
import rdflib
import oxrdflib

DATA = """
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
<test> rdfs:label "test".
"""
QUERY = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?label {<test> rdfs:label ?label.}
"""
graph = rdflib.Graph(store="Oxigraph")
graph.parse(data=DATA,format="ttl")
graph.query(QUERY)
```
## Console Output
```
$python test.py
Traceback (most recent call last):
  File "/home/konrad/tmp/test.py", line 16, in <module>
    graph.query(QUERY)
  File "/home/konrad/.local/lib/python3.10/site-packages/rdflib/graph.py", line 1311, in query
    return self.store.query(
  File "/home/konrad/.local/lib/python3.10/site-packages/oxrdflib/__init__.py", line 78, in query
    result = self._inner.query(
SyntaxError: error at 3:24: expected OPTIONAL
```

The error does not occur when not using a prefixed instead of an absolute URI:

```
import rdflib
import oxrdflib

DATA = """
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
<test> rdfs:label "test".
"""
QUERY = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?label {rdfs:test rdfs:label ?label.}
"""
graph = rdflib.Graph(store="Oxigraph")
graph.parse(data=DATA,format="ttl")
graph.query(QUERY)
```

**Comment by KonradHoeffner** [comment]
Adding `BASE <http://example.com/>` fixes the problem, thanks!
